# A generic, single database configuration.

[alembic]
# путь к папке с миграциями
script_location = alembic

# шаблон имени файлов миграций
file_template = %%(rev)s_%%(slug)s

# временная зона
timezone = UTC

# максимальная длина слага
truncate_slug_length = 40

# авто-генерация миграций
revision_environment = true

# версии (обычно не меняется)
version_locations = %(here)s/alembic/versions

# кодировка
output_encoding = utf-8

# URL задаётся через переменную окружения DATABASE_URL в env.py
# sqlalchemy.url = driver://user:pass@localhost/dbname

[post_write_hooks]
hooks = black
black.type = console_scripts
black.entrypoint = black
black.options = -l 88

# настройки логирования
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
